### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by sharathsp93** [r-link/microtome_slides#2]
"Ctrl + D" helps to set the default background colour (black and white)

**Comment by r-link** [comment]
Sure? according to [this page](https://www.gimpusers.com/gimp/hotkeys) Ctrl + D duplicates the image. This is also what happened when I tried it. D does the job, but only without Ctrl.

**Comment by sharathsp93** [comment]
Okay! I think it is dependent on the keyboard.
